export default {
    "data": [
        {
            "id": 76,
            "createdAt": "2019-10-09 17:27:46",
            "updatedAt": "2019-10-29 10:30:57",
            "archive": false,
            "code": "XM001",
            "name": "美白",
            "shopId": "168",
            "imgs": "89a580f8-ce09-410e-a203-114b1e189cac.png",
            "marketPrice": 599,
            "discountPrice": 0.01,
            "stock": null,
            "sals": null,
            "productStatus": "1",
            "typeStatus": "1",
            "customSort": null,
            "categoryId": 81,
            "productBaseId": 19,
            "productBaseName": "美白保湿补水",
            "status": null,
            "bbSkus": [
                {
                    "id": 111,
                    "createdAt": "2019-10-09 17:27:46",
                    "updatedAt": "2019-10-29 10:30:57",
                    "archive": false,
                    "productBsId": 76,
                    "skuCode": "MAN002",
                    "skuName": "欧莱雅面霜15ML",
                    "productName": "欧莱雅面霜",
                    "skuImgs": null,
                    "stock": 1000,
                    "marketPrice": 499,
                    "discountPrice": 499,
                    "attributes": null,
                    "detail": null,
                    "costPrice": null,
                    "number": 10,
                    "specsCov": null,
                    "specs": 1,
                    "standardUnit": "6",
                    "minUnit": "4",
                    "type": "1",
                    "shopId": "168",
                    "skuLossId": 109
                },
                {
                    "id": 112,
                    "createdAt": "2019-10-09 17:27:46",
                    "updatedAt": "2019-10-29 10:30:57",
                    "archive": false,
                    "productBsId": 76,
                    "skuCode": "MAA001",
                    "skuName": "欧莱雅面霜10ML",
                    "productName": "欧莱雅面霜",
                    "skuImgs": null,
                    "stock": 1000,
                    "marketPrice": 399,
                    "discountPrice": 399,
                    "attributes": null,
                    "detail": null,
                    "costPrice": null,
                    "number": 10,
                    "specsCov": null,
                    "specs": 1,
                    "standardUnit": "6",
                    "minUnit": "4",
                    "type": "1",
                    "shopId": "168",
                    "skuLossId": 110
                }
            ]
        },
        {
            "id": 81,
            "createdAt": "2019-10-11 13:41:41",
            "updatedAt": "2019-10-11 13:41:41",
            "archive": false,
            "code": "XM002",
            "name": "SPA排毒",
            "shopId": "168",
            "imgs": "34587fae-1b0a-49c7-ac95-3420bb1076cb.jpg",
            "marketPrice": 899,
            "discountPrice": 699,
            "stock": null,
            "sals": null,
            "productStatus": "1",
            "typeStatus": "1",
            "customSort": null,
            "categoryId": 81,
            "productBaseId": 18,
            "productBaseName": "SPA排毒",
            "status": null,
            "bbSkus": [
                {
                    "id": 121,
                    "createdAt": "2019-10-11 13:41:41",
                    "updatedAt": "2019-10-11 13:41:41",
                    "archive": false,
                    "productBsId": 81,
                    "skuCode": "MAN002",
                    "skuName": "欧莱雅面霜15ML",
                    "productName": "欧莱雅面霜",
                    "skuImgs": null,
                    "stock": 0,
                    "marketPrice": 499,
                    "discountPrice": 499,
                    "attributes": null,
                    "detail": null,
                    "costPrice": null,
                    "number": 10,
                    "specsCov": null,
                    "specs": 1,
                    "standardUnit": "6",
                    "minUnit": "4",
                    "type": "1",
                    "shopId": "168",
                    "skuLossId": 109
                },
                {
                    "id": 122,
                    "createdAt": "2019-10-11 13:41:41",
                    "updatedAt": "2019-10-11 13:41:41",
                    "archive": false,
                    "productBsId": 81,
                    "skuCode": "MAA001",
                    "skuName": "欧莱雅面霜10ML",
                    "productName": "欧莱雅面霜",
                    "skuImgs": null,
                    "stock": 0,
                    "marketPrice": 399,
                    "discountPrice": 399,
                    "attributes": null,
                    "detail": null,
                    "costPrice": null,
                    "number": 10,
                    "specsCov": null,
                    "specs": 1,
                    "standardUnit": "6",
                    "minUnit": "4",
                    "type": "1",
                    "shopId": "168",
                    "skuLossId": 110
                }
            ]
        }
    ]
}